//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMONTRUNGTAM
    {
        public int MaBm { get; set; }
        public string TenBM { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> Fax { get; set; }
        public Nullable<int> SDT { get; set; }
        public string Email { get; set; }
    }
}
