//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIANGVIEN
    {
        public int MaGV { get; set; }
        public Nullable<int> MaBM { get; set; }
        public string TenGV { get; set; }
        public string ChucVu { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DiaChi { get; set; }
        public string MonHocPhuTrach { get; set; }
        public string TrinhDoHocVan { get; set; }
    }
}
