//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHLAMVIEC
    {
        public int STT { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<int> CongViec { get; set; }
        public Nullable<int> Tuan { get; set; }
        public string Thu { get; set; }
        public string DiaChi { get; set; }
    }
}
